  language: ruby
  rvm:
    - 1.9.3
    - jruby-18mode # JRuby in 1.8 mode
    - jruby-19mode # JRuby in 1.9 mode
    - rbx-2.1.1
    - 1.8.7
  deploy:
     provider: heroku
     api_key: "bb154dca-b45a-45b2-af19-cee3f62e244c"

# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec